# Generated by Django 5.1.2 on 2025-11-01 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_transportroute_options_vehiclelocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportroute',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelocation',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiclelocation',
            name='speed_kmh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelocation',
            name='status',
            field=models.CharField(choices=[('moving', 'Moving'), ('stopped', 'Stopped'), ('idle', 'Idle'), ('offline', 'Offline')], default='moving', max_length=16),
        ),
        migrations.AlterField(
            model_name='vehiclelocation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
