import {
  FaUsers,
  FaShoppingCart,
  FaTruck,
  FaChartLine,
  FaCog,
  FaEye,
  FaEdit,
  FaTrash,
  FaCheck,
  FaTimes,
  FaSearch,
  FaFilter,
  FaDownload,
  FaMapMarkerAlt,
  FaCalendarAlt,
  FaPhone,
  FaEnvelope,
  FaIdCard,
  FaHome,
  FaUser,
  FaBell,
  FaSignOutAlt,
} from 'react-icons/fa';

export const ICONS = {
  users: FaUsers,
  orders: FaShoppingCart,
  transport: FaTruck,
  analytics: FaChartLine,
  settings: FaCog,
  view: FaEye,
  edit: FaEdit,
  delete: FaTrash,
  check: FaCheck,
  close: FaTimes,
  search: FaSearch,
  filter: FaFilter,
  download: FaDownload,
  map: FaMapMarkerAlt,
  calendar: FaCalendarAlt,
  phone: FaPhone,
  email: FaEnvelope,
  id: FaIdCard,
  home: FaHome,
  user: FaUser,
  bell: FaBell,
  logout: FaSignOutAlt,
};
